### ISSUE TITLE
Is it possible for `disable-next-line` as eslint?

### ISSUE THREAD

**Issue by Mister-Hope** [textlint/textlint-filter-rule-comments#9]

**Comment by azu** [comment]
Currently, it is not implemented.

My concern is that some parser a new line between comment and the next line.
For example, some markdown parser requires a empty new line between HTML comment and next line.

```markdown
<!-- text-disable-next-line -->

text text.
```

In this case, `next-line` is misleading words.

**Comment by Mister-Hope** [comment]
Yes, we should concren that. I think it should be on line 3, if users do want two or more empty line, they should write:

```md
This is error text.

<!-- textlint-disable -->


<!-- textlint-enable -->

This is error text.
```

I cannot think off other cases which will force users to disable an empty line.

I think the methods can be:

1. if the next line is an empty line, go to the second one.
2. if the line only contains comments and contains `-disable` `enable` or `disable-next-line`
3. diable in next line than enable it.

Any problems above?

**Comment by azu** [comment]
Ok.

I'm not sure if `next-line` is the correct word.

Probably, `next-ast-node` is correct, but it is not a generic word.
https://textlint.github.io/astexplorer/

https://github.com/eslint/eslint/blob/4a091495a236d231a5065ece972719a0c4dd1b77/lib/linter/apply-disable-directives.js#L139-L143
eslint just use `line + 1`. textlint cant not do that, because, empty line has meaning in some syntax like markdown.
